### ISSUE TITLE
I can't download the module.

### ISSUE THREAD

**Issue by kaganege** [TooTallNate/node-lame#107]
## Hello first of all.

When I try to download the module it gives [this](https://www.toptal.com/developers/hastebin/zikumewudo.swift) error. (I couldn't get ss because the error was too long)

Thanks for your help in advance.

**Comment by kaganege** [comment]
Node Version: v16.15.1
Npm Version: 8.11.0
node-gyp Version: 9.1.0

**Comment by leonardoamaro-dev** [comment]
me too

**Comment by kaganege** [comment]
> me too

@leonardoamaro-dev https://github.com/TooTallNate/node-lame/issues/92#issuecomment-585967445
