### ISSUE TITLE
Fails to build for node-webkit 0.11.5

### ISSUE THREAD

**Issue by sarangsapre** [TooTallNate/node-lame#40]
Command : 

nw-gyp clean configure --target=0.11.5  build --arch=ia32

Some of the Errors : 

gyp info using nw-gyp@0.12.4
gyp info using node@0.10.30 | win32 | ia32

..\src\node_mpg123.cc(497): error C2661: 'v8::Object::Set' : no overloaded func
tion takes 3 arguments [d:\matlabintegration\node-modules\node-lame\build\bindi
ngs.vcxproj]
..\src\node_mpg123.cc(498): error C2661: 'v8::Object::Set' : no overloaded func
tion takes 3 arguments [d:\matlabintegration\node-modules\node-lame\build\bindi
ngs.vcxproj]

..\src\node_mpg123.cc(35): error C2062: type 'int' unexpected [d:\matlabintegration\node-modules\node-lame\build\bindings.vcxproj]

1. Looks like we need to use ForceSet instead of Set?

2. Do we need this min() anymore ?

**Comment by TooTallNate** [comment]
Fixed by #41.
