### ISSUE TITLE
Other Sampling Rates

### ISSUE THREAD

**Issue by pedromtavares** [TooTallNate/node-lame#6]
Yo Nate! :)

So I'm back to working on my radio website that I've talked to you about in the past, but fortunately my question today is quite small!

The issue is that I'm streaming mp3 files from all over the internet, and thus, they don't come in a same pretty pattern, they all have completely different bit rates and sampling rates. The bit rate problem I managed to solve, but the sampling rates problem sort of depends on this lib, hehe.

https://github.com/TooTallNate/node-lame/blob/master/lib/parse.js#L30

This array only allows those sampling rates, and when a file comes with a sampling rate of say 22050 (I'm spawning a process of ffprobe to figure out this info on a track), then it bugs everything and doesn't run, haha.

To make a big story short, is adding new sampling rates as easy as adding numbers to that array? Or is the issue deeper than that?

By the way, I'll be writing a huge blog post about the part 2 of the radio website and you can expect another big thank you in there :P

Cheers,

**Comment by darkyen** [comment]
For anyone messing with sample rates there exists node-resampler (libresample) and node-samplerate (libsamplerate) both are backed by incredibly well maintained and performant native modules. I would recommend using them if you are still having a resample issue.
