### ISSUE TITLE
Can this work in realtime?

### ISSUE THREAD

**Issue by darkyen** [TooTallNate/node-lame#63]
Just wondering if I can encode / decode audio in chunks of n ms?

I mean I assume this being a stream subclass will respect if I only give it parts of the stream. Just wanted to make sure. <: 

Also any suggestions how to re-sample / mux audios.

**Comment by darkyen** [comment]
Works like a bliss in realtime. :dancers: :dancers:

**Comment by BurakDev** [comment]
@darkyen Really ? how many ms you get ?
